### PR TITLE
build softIocPVA

### PR DESCRIPTION
**Pull request by mdavidsaver**
Copy the softMain.cpp from Base and build as softIocPVA.  Modified to automatically start the PVA server.

### CODE REVIEW

**Comment by anjohnson** [comment]
You may need a copy of `makeInstallDir.pl` and the rules (3.14 & 3.15) for creating `epicsInstallDir.h`. On discovering that the Windows shell does strange things to quotes and escapes on on the command-line and having to support install paths that may include spaces on Windows, I concluded that getting the FINAL_LOCATION string value properly defined as a CPP macro on all build platforms was just too difficult, which is why I punted and did it in Perl in Base.

**Comment by mdavidsaver** [comment]
Fixed build failure against Base 3.14.x

**Comment by ralphlange** [comment]
retest this please

**Comment by ralphlange** [comment]
retest this please

**Pull request merged**
