### PR TITLE
fixed 3.15 security plugin issue w/ multiple providers

### PR DESCRIPTION
**Pull request by msekoranja**
(a missing code change when porting 3.14 security plugin to 3.15)

### CODE REVIEW

**Comment by msekoranja** [comment]
this is a fix for #31

**Comment by mdavidsaver** [comment]
I know this is supposed to be a short term fix, but comparing exception strings is a really ugly hack.  Since this is all done within caSecurity.h it's not difficult to sub-class SecurityException as eg. NoRecordException and catch this in createChannelSession().  Absent this, imo. a comment needs to be added in the CAServerChannelSecuritySession ctor to the effect that the exception string is special.

```c++
struct NoRecordException : public SecurityException
{
    NoRecordException() : SecurityException("No such record") {}
};
```

**Comment by anjohnson** [comment]
What @mdavidsaver said. Comparing exception message strings like this is a bad code smell, the exception needs to be split into different types that can be distinguished by different catch blocks.

**Comment by msekoranja** [comment]
@mdavidsaver @anjohnson I totally agree this is one of the ugliest code possible, I just did want to introduce any additional code/classes for a workaround. I'll provide a nicer patch.

**Comment by msekoranja** [comment]
nicer bugfix commited

**Comment by mdavidsaver** [comment]
> nicer bugfix commited

looks good.

**Comment by anjohnson** [comment]
Much better, thanks.

**Pull request merged**
