### PR TITLE
pv/ sub-directories

### PR DESCRIPTION
**Pull request by mdavidsaver**
As per epics-base/pvDataCPP#15.

### CODE REVIEW

**Comment by anjohnson** [comment]
**HOLD** @mdavidsaver Don't move include files into pv/ that weren't already being installed there.

The headers in pvaSrv are not a published API of V4, and I believe Ralph was quite deliberate in *not* putting them under pv/. That may not apply to the dbGroup directory (which was Marty's code and IIRC is a deprecated interface now anyway), but for the IOC-related code I remember talking about this with Ralph. 

IMHO you should not be modifying any include statements in C/C++ code. Such moves were not necessary to fix the original purpose of these changes. This may apply to other include files in other modules too, so I think we need to look closely at any includes you have already changed.

**Comment by mdavidsaver** [comment]
> Don't move include files into pv/ that weren't already being installed there.

I have not done so.

```sh
for make in */Makefile; do grep INC $make|cut -f3 -d ' ' | while read ff; do install -d `dirname $make`/pv; git mv `dirname $make`/$ff `dirname $make`/pv/$ff; done; done
```

I used a little script which only moves those headers in $(INC) in a Makefile.

**Comment by anjohnson** [comment]
Then why did you have to add "pv/" to some `#include` statements? My built pvaSrv installation doesn't have an include/pv directory at all.

**Comment by mdavidsaver** [comment]
Oh, I see.  None of the headers were being installed in pv/.  Well fair enough, and never mind...

**Pull request closed without merging**
