### PR TITLE
initialize block in constructor

### PR DESCRIPTION
**Pull request by mrkraimer**
In the dbPvGet constructor block was not initialized.

The following is the fix
diff --git a/src/dbPv/3.14/dbPvGet.cpp b/src/dbPv/3.14/dbPvGet.cpp
index 4518ce0..ac5d76b 100644
--- a/src/dbPv/3.14/dbPvGet.cpp
+++ b/src/dbPv/3.14/dbPvGet.cpp
@@ -42,6 +42,7 @@ DbPvGet::DbPvGet(
   process(false),
   firstTime(true),
   propertyMask(0),
+  block(true),
   beingDestroyed(false)
 {
     if(DbPvDebug::getLevel()>0)printf("dbPvGet::dbPvGet\n");
diff --git a/src/dbPv/3.15/dbPvGet.cpp b/src/dbPv/3.15/dbPvGet.cpp
index 257d7b6..9e91efe 100644
--- a/src/dbPv/3.15/dbPvGet.cpp
+++ b/src/dbPv/3.15/dbPvGet.cpp
@@ -40,6 +40,7 @@ DbPvGet::DbPvGet(
   process(false),
   firstTime(true),
   propertyMask(0),
+  block(true),
   beingDestroyed(false)
 {
     if(DbPvDebug::getLevel()>0)printf("dbPvGet::dbPvGet\n");

### CODE REVIEW

**Comment by ralphlange** [comment]
Not convinced that initializing it to `true` is the right thing to do.

The code in `DbPvGet::init()` (line 91)
    `if (propertyMask & dbUtil->blockBit) block = true;`
only makes sense if `block` is initialized to `false`, don't you think?

Do we have a specification that `block` defaults `true` for get operations?

**Comment by dhickin** [comment]
Completely agree with Ralph. block must either be

1.  initialized to false
or 
2. set to false/true if blockBit clear/set in .

Better it should be initialised to default value and then set to the other value depending on blockBit.

**Comment by mrkraimer** [comment]
On 02/26/2016 07:20 AM, Ralph Lange wrote:
>
> Not convinced that initializing it to |true| is the right thing to do.
>
> The code in |DbPvGet::init()| (line 91)
> |if (propertyMask & dbUtil->blockBit) block = true;|
> only makes sense if |block| is initialized to |false|, don't you think?
>
> Do we have a specification that |block| defaults |true| for get 
> operations?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-base/pvaSrv/pull/30#issuecomment-189253910>.
>

Agreed.
Also the order was wrong in the constructor.

I made the change and pushed in mrkraimer

**Comment by ralphlange** [comment]
According to ISO/IEC 14882:2003(E) section 12.6.2, nonstatic data members shall be initialized in the order they were declared in the class definition (regardless of the order of the mem-initializers).

I.e. there is no wrong order in the constructor's mem-initializers - it just doesn't matter.

**Comment by ralphlange** [comment]
FWIW:

Your intermediate merge of the epics-base master was not strictly necessary. Pull requests are always shown against the target, and the CloudBees PR builds are building the result of the proposed merge, not the branch for that the pull is being requested.

Only if the PR builds fail, merging the target makes sense. This allows to resolve conflicts and fix problems on the source branch, before the merge.

**Comment by anjohnson** [comment]
> I.e. there is no wrong order in the constructor's mem-initializers - it just doesn't matter.

True, but to avoid misleading any humans reading the code it is good practice for the initializer list in the constructor to follow the order used in the class declaration. Recent versions of g++ warn when those orders are different for exactly this reason.

**Pull request merged**
